
# **Topic: Python Packages-- Numpy**
**Content Creator(s):**  Precious Darkwa

**Content Reviewer(s):** Deborah D Kanubala, Ahmad Bilesanmi, Salomey Osei



## **Content**

1. [What is Numpy](#numpy)


2. [Advantages of Numpy](#advantages)


3. [Numpy Installations](#installations)


4. [Numpy Array](#arrays)


5. [Sorting an Array](#sorting)

6. [Mathematical Operations with Arrays](#operations)

7. [Broadcasting](#broadcasting)

8. [Numpy Indexing and Selection](#indexing)



---
<a name="numpy"></a>
### **What is Numpy**

Numpy stands for Numerical Python.

It is a popular Python library built on C programming which is used for scientific computing.



---
<a name="advantages"></a>
### **Advantages of Numpy**


- Numpy array manipulations are faster as compared to the list data structure.
- Numpy provides a wide range of universal functions for performing element-wise opperations on arrays such as addition, multiplicaton 
- NumPy provides a powerful and flexible data structure called ndarrays (N-dimensional arrays), which can represent and manipulate data in multiple dimensions.
- NumPy's broadcasting feature allows arrays with different shapes to be used in arithmetic operations, which can greatly simplify code and reduce memory usage.




---
<a name="installations"></a>
### **Installation of Numpy**

The numpy library can be installed using the following:


**1. Command Prompt**

- Launch the command prompt
- Type the code below to install the numpy library

`pip install numpy`



**2. Anaconda Terminal**

- Launch the anaconda terminal
- Type the code below to install the numpy library

`conda install numpy`


### Using Numpy

To use the numpy library import the numpy library using:

`import numpy as np`

The **np** is the popular alias for the numpy library.

In [1]:
import numpy as np




---
<a name="arrays"></a>
### **Numpy Arrays**

A numpy array is a grid of values with the same data type and that is indexed by a tuple of non-negative integers.

Numpy arrays can havr any number of dimensions, but the most popular types are the one dimensional array(vectors) and two dimensional arrays(matrices)

#### **Creating  a 1D array**

In [ ]:
arr_1 = np.array([1,2,3,4])

In [ ]:
arr_1

array([1, 2, 3, 4])

In [ ]:
#Check the dimension of the array
arr_1.ndim

1

In [ ]:
#check the shape of the array
arr_1.shape

(4,)

#### **Creating a 1D array from a list**

In [ ]:
ls_1 = [2,3,4,5]

In [ ]:
arr_2 = np.array(ls_1)

In [ ]:
arr_2

array([2, 3, 4, 5])

In [ ]:
arr_2.shape

(4,)

In [ ]:
#Get the data type of the array
type(arr_2)

numpy.ndarray



---
<a name="sorting"></a>
### **Sorting an array**

In [ ]:
arr_7 = np.array([5,6,3,2,9])
arr_7

array([5, 6, 3, 2, 9])

In [ ]:
np.sort(arr_7)

array([2, 3, 5, 6, 9])

In [ ]:
np.sort(arr_7)[::-1]

array([9, 6, 5, 3, 2])

In [ ]:
arr_8= np.array([[3,6,5],[4,6,7],[1,6,8]])
arr_8

array([[3, 6, 5],
       [4, 6, 7],
       [1, 6, 8]])

In [ ]:
#sorting by columns
np.sort(arr_8,axis=1)

array([[3, 5, 6],
       [4, 6, 7],
       [1, 6, 8]])

In [ ]:
#sorting by row
np.sort(arr_8,axis=0)

array([[1, 6, 5],
       [3, 6, 7],
       [4, 6, 8]])



---
<a name="operations"></a>
### **Mathematical Operations with Arrays**

In [ ]:
a = np.array([[2,4], [6,8]])
b = np.array([[1,7],[2,4]])

In [ ]:
a

array([[2, 4],
       [6, 8]])

In [ ]:
b

array([[1, 7],
       [2, 4]])

In [ ]:
#addition
a+b

array([[ 3, 11],
       [ 8, 12]])

In [ ]:
#subtraction
a-b

array([[ 1, -3],
       [ 4,  4]])

In [ ]:
#multiplcation
a*b

array([[ 2, 28],
       [12, 32]])

In [ ]:
b*a

array([[ 2, 28],
       [12, 32]])

In [ ]:
# Division
a/b

array([[2.        , 0.57142857],
       [3.        , 2.        ]])



---
<a name="broadcasting"></a>
## **Broadcasting**

In [ ]:
d = 5
arr_a = np.array([[5,6],[4,2]])
arr_b = np.array([2,3])

In [ ]:
d

5

In [ ]:
arr_a

array([[5, 6],
       [4, 2]])

In [ ]:
arr_b

array([2, 3])

In [ ]:
#scalar with array
d * arr_a

array([[25, 30],
       [20, 10]])

In [ ]:
d + arr_a

array([[10, 11],
       [ 9,  7]])

In [ ]:
# adding arrays with different shapes
arr_a +arr_b

array([[7, 9],
       [6, 5]])

In [ ]:
arr_a *arr_b

array([[10, 18],
       [ 8,  6]])

In [ ]:
arr_b*arr_a

array([[10, 18],
       [ 8,  6]])



---
<a name="indexing"></a>
## **Numpy Indexing and Selection**

Numpy indexing is similar to indexing in list data structure.

For a 1D array, elementss are accessed using their integer indicies

In [ ]:

arr_3 = np.arange(5,40,5)
arr_3

array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
# get the first element of arr_3
arr_3[0]

5

In [ ]:
# get the third element of arr_3
arr_3[2]

15

In [ ]:
# get the last element of arr_3
arr_3[-1]

35

In a 2D array, a pair of indicies separated by a conna to access individual elements.


In [ ]:
array_4 = np.array([[2,5,6],[3,4,5]])

In [ ]:
array_4

array([[2, 5, 6],
       [3, 4, 5]])

In [ ]:
#Selecting the element in the first row and third column
array_4[0,2]

6

In [ ]:
#Selecting the element in the second row and second column
array_4[1,1]

4

### **Slicing Arrays**

In [ ]:
arr_3

array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
#The first three elements of arr_3
arr_3[:3]

array([ 5, 10, 15])

In [ ]:
arr_3[1:5:2]

array([10, 20])

In [ ]:
arr_3[3:6]

array([20, 25, 30])

In [ ]:
mat_A = np.array(([3,6,9],[12,15,18],[21,24,27]))

In [ ]:
mat_A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [ ]:
#Getting all elements in the second row
mat_A[1,:]

array([12, 15, 18])

In [ ]:
#Getting all elements in the second column
mat_A[:,1]

array([ 6, 15, 24])

In [ ]:
mat_A[2,1]

24

In [ ]:
#Updating an element
mat_A[2,1] = 0

In [ ]:
mat_A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21,  0, 27]])

In [ ]:
np.delete(mat_A, 0, axis =1)

array([[ 6,  9],
       [15, 18],
       [ 0, 27]])

In [ ]:
mat_A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21,  0, 27]])

In [ ]:
np.delete(mat_A, 2, axis =0)

array([[ 3,  6,  9],
       [12, 15, 18]])

### **Boolean Indexing**

Selecting elements from an array that meet a certain condition.

The boolean condition is an expression that returns a true or false value for each element in an array.

In [ ]:
array_5 = np.array([4,3,2,8])

In [ ]:
#Selecting elements of array_5 greater than 3
array_5[array_5>3]

array([4, 8])

In [ ]:
#Selecting elements of array_5 that is evenly divided by 2
array_5[array_5%2==0]

array([4, 2, 8])

In [ ]:
#Selecting elements of array_5 less than 3

array_5[array_5<3]

array([2])

#### **arange**

It is a function that provdies a  1D array of evenly spaced values within a specific range.

The value of the stop is exclusive

The deafult step size between values is 1.

It has the following syntax:

`np.arange(stop)`

`np.arange(start,stop )`

`np.arange(start,stop,step)`


In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

**linspace**

It is used to create a 1D array of evenly spaced values within a specified interval, with a specificed number of elements.

In [ ]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [ ]:
np.linspace(0,50,10, endpoint=False)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [ ]:
np.linspace(20,30,10)

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

### **Universal Function**

In [ ]:
arr_9 = np.array([3,4,5,3,2,4,3,4,3])

In [ ]:
np.sum(arr_9)

31

In [ ]:
np.min(arr_9)

2

In [ ]:
np.max(arr_9)

5

In [ ]:
np.mean(arr_9)

3.4444444444444446

In [ ]:
np.median(arr_9)

3.0

In [ ]:
np.sqrt(arr_9) 

array([1.73205081, 2.        , 2.23606798, 1.73205081, 1.41421356,
       2.        , 1.73205081, 2.        , 1.73205081])

In [ ]:
arr_10 = np.array([[3,4,5,3,2,4,3,4,3],[2,9,5,3,2,8,3,4,8]])
arr_10

array([[3, 4, 5, 3, 2, 4, 3, 4, 3],
       [2, 9, 5, 3, 2, 8, 3, 4, 8]])

In [ ]:
arr_10.shape

(2, 9)

In [ ]:
np.sum(arr_10,axis=0)

array([ 5, 13, 10,  6,  4, 12,  6,  8, 11])

In [ ]:
np.sum(arr_10,axis=1)

array([31, 44])

---
#Congrats! That's it for this tutorial.

---
<h1> Author(s):</h1> 

 
**Precious Darkwa**, Data Science/Analytics Instructor @ Blossom Academy  

Email: preciousdarkwa@gmail.com 

---

*This notebook was originally created by Ghana Data Science Summit for the [IndabaX Ghana](https://www.indabaxghana.com/) 2023 Conference and is published under [MIT license](https://choosealicense.com/licenses/mit/).*